name: rating_dialog
description: A beautiful and customizable Star Rating Dialog package for Flutter
version: 2.0.3
homepage: https://github.com/nemoryoliver/rating_dialog

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
